server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  prefix: /api

management:
  endpoints:
    web:
      exposure:
        include: health,routes