server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/poc

management:
  endpoints:
    web:
      exposure:
        include: health,routes,info,hystrix.stream

ribbon:
  eager-load:
    enabled: true