server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  prefix: /api
  routes:
    resource-service-one:
      sensitive-headers: Cookie,Set-Cookie


management:
  endpoints:
    web:
      exposure:
        include: health,routes,info

ribbon:
  eager-load:
    enabled: true