server:
  port: 0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/poc

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8151/eureka/
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}